service: elliott-kinesis

# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - kinesis:*
      Resource:
        - arn:aws:kinesis:ap-southeast-2:773592622512:stream/elliott-test
  runtime: nodejs10.x
  region: ap-southeast-2

functions:
  pushEvent:
    handler: handler.pushEvent
    environment:
      OUR_STREAM: elliott-test
    events:
      - http:
          path: event
          method: get

  processEvent:
    handler: process.processEvent
    events:
      - stream:
          type: kinesis
          arn: arn:aws:kinesis:ap-southeast-2:773592622512:stream/elliott-test
          batchSize: 2
            # Fn::ImportValue: MyExportedKinesisStreamArnId

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
